import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import RightSidebar from "@/components/RightSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="portfolio">
          <div className="left">
            <Sidebar />
          </div>
          <div className="right">
            <RightSidebar />
            <div className="content">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
